#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
APP="$1";  IMAGE="dokku/$APP"

JSPMSCRIPT="
#!/bin/bash

cd /app/client
PATH=\$PATH:/app/vendor/node/bin
if [[ -f ./package.json ]]; then
	npm install -g jspm && ./jspmRegistry.sh && jspm install -y && jspm bundle aurelia-bootstrapper + aurelia-http-client + aurelia-dependency-injection + aurelia-router dist/app-bundle.js --inject --minify --skip-source-maps
fi
"

echo '-----> Injecting jspm script'
id=$(echo "$JSPMSCRIPT" | docker run -i -a stdin $IMAGE /bin/bash -c "cat > /app/.jspm")
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
id=$(docker run -d $IMAGE /bin/bash -c "chmod +x /app/.jspm")
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
